name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # ⬇️ Inject AWS credentials for Terraform to use
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2  # or your desired region

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -input=false
        env:
          TF_LOG: DEBUG

      - name: Terraform Format
        run: terraform fmt -check
        env:
          TF_LOG: DEBUG

      - name: Terraform Validate
        run: terraform validate
        env:
          TF_LOG: DEBUG

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false
        env:
          TF_LOG: DEBUG

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -input=false -auto-approve tfplan
        env:
          TF_LOG: DEBUG
